Update lumina-config_sv.ts
lumina-desktop/lumina pull request #754
Opened 2021-05-11 07:44 UTC by bittin

Updated Swedish Translation 98%

2021-05-11 12:47 UTC, beanpole135 requested changes
All of these translations are in the wrong spot and will not be used they way they are now.
The `type="unfinished"` tag needs to be removed, and the translated text put between the tags like this:
`<translation>This is translated text</translation>`

2021-05-11 17:22 UTC, beanpole135 requested changes
Got a few issues with this one still.
I suggested changes for some of them, the others just need to be finished it looks like.

2021-05-11 17:22 UTC, beanpole135 commented on src-qt5/core-utils/lumina-config/i18n/lumina-config_sv.ts
> +        <source>Change grundläggande ljudinställningar</source>
```suggestion
        <source>Change basic sound settings</source>
```
Do not change the "source" text - that could result in the translation not getting applied properly.

2021-05-11 17:22 UTC, beanpole135 commented on src-qt5/core-utils/lumina-config/i18n/lumina-config_sv.ts
> +        <translation>System">System</translation>
```suggestion
        <translation>System</translation>
```

2021-05-11 17:22 UTC, beanpole135 commented on src-qt5/core-utils/lumina-config/i18n/lumina-config_sv.ts
> +        <translation>unfinished</translation>
This needs to be finished, or reverted back to having the `type="unfinished"` tag.

2021-05-11 17:22 UTC, beanpole135 commented on src-qt5/core-utils/lumina-config/i18n/lumina-config_sv.ts
> +        <translation>unfinished</translation>
This needs to be finished, or reverted back to having the `type="unfinished"` tag.

2021-05-11 17:22 UTC, beanpole135 commented on src-qt5/core-utils/lumina-config/i18n/lumina-config_sv.ts
> +        <translation>unfinished</translation>
This needs to be finished, or reverted back to having the `type="unfinished"` tag.

2021-05-11 17:22 UTC, beanpole135 commented on src-qt5/core-utils/lumina-config/i18n/lumina-config_sv.ts
> +        <translation>unfinished</translation>
This needs to be finished, or reverted back to having the `type="unfinished"` tag.

2021-05-11 17:22 UTC, beanpole135 commented on src-qt5/core-utils/lumina-config/i18n/lumina-config_sv.ts
> +        <translation>Fönsterhanterare">Fönsterhanterare</translation>
```suggestion
        <translation>Fönsterhanterare</translation>
```

2021-05-11 17:22 UTC, beanpole135 commented on src-qt5/core-utils/lumina-config/i18n/lumina-config_sv.ts
> +        <translation>Formulär">Formulär</translation>
```suggestion
        <translation>Formulär</translation>
```

2021-05-11 17:22 UTC, beanpole135 commented on src-qt5/core-utils/lumina-config/i18n/lumina-config_sv.ts
> +        <translation>unfinished</translation>
This needs to be finished, or reverted back to having the `type="unfinished"` tag.

2024-01-02 02:24 UTC, q5sys commented
This work has been redone with later PRs

2024-01-02 02:24 UTC, closed without merging