Update lumina-desktop_sv.ts
lumina-desktop/lumina pull request #755
Opened 2021-05-11 07:59 UTC by bittin

Updated Swedish translation

2021-05-11 17:25 UTC, beanpole135 requested changes
A ton of these have duplication translation strings with half-tags.
I suggested fixes for a couple of them, but you will need to go through and fix the others the same way.

2021-05-11 17:25 UTC, beanpole135 commented on src-qt5/core/lumina-desktop/i18n/lumina-desktop_sv.ts
> +        <translation>Starta %1">Starta %1</translation>
```suggestion
        <translation>Starta %1</translation>
```

2021-05-11 17:25 UTC, beanpole135 commented on src-qt5/core/lumina-desktop/i18n/lumina-desktop_sv.ts
> +        <translation>Skrivbord">Skrivbord</translation>
```suggestion
        <translation>Skrivbord</translation>
```

2024-01-02 02:25 UTC, q5sys commented
This work has been redone with later PRs

2024-01-02 02:25 UTC, closed without merging