Added Swedish Translation
lumina-desktop/lumina pull request #758
Opened 2021-05-11 08:14 UTC by bittin

2021-05-11 12:46 UTC, beanpole135 requested changes
All of these translations are in the wrong spot and will not be used they way they are now.
The `type="unfinished"` tag needs to be removed, and the translated text put between the tags like this:
`<translation>This is translated text</translation>`

2021-05-11 17:42 UTC, beanpole135 requested changes
Looks like you got some more stray `<` and `">` in here on the translation lines.
I suggested changes for the first couple to get you started, but you will need to fix up the rest too.

2021-05-11 17:42 UTC, beanpole135 commented on src-qt5/desktop-utils/lumina-photo/i18n/l-photo_sv.ts
> +        <<translation>Bildvisare></translation>
```suggestion
        <translation>Bildvisare</translation>
```

2021-05-11 17:42 UTC, beanpole135 commented on src-qt5/desktop-utils/lumina-photo/i18n/l-photo_sv.ts
> +        <<translation>&amp; Fil"></translation>
```suggestion
        <translation>&amp; Fil</translation>
```

2021-05-12 05:48 UTC, bittin commented
fixed

2021-05-12 15:37 UTC, beanpole135 approved these changes
Looks good!
Thanks for getting that cleaned up!

2021-05-12 15:37 UTC, merged