Update l-te_sv.ts
lumina-desktop/lumina pull request #759
Opened 2021-05-11 08:21 UTC by bittin

Updated Swedish translation

2021-05-11 12:45 UTC, beanpole135 requested changes
All of these translations are in the wrong spot and will not be used they way they are now.
The `type="unfinished"` tag needs to be removed, and the translated text put between the tags like this:
`<translation>This is translated text</translation>`

2021-05-11 17:44 UTC, beanpole135 requested changes
Looks like quoting and `<` errors in here still.
I suggested fixes for the first couple to get you started, but you will need to fix the rest too.

2021-05-12 05:46 UTC, bittin commented
fixed

2021-05-12 16:04 UTC, beanpole135 approved these changes

2021-05-12 16:04 UTC, beanpole135 commented on src-qt5/desktop-utils/lumina-textedit/i18n/l-te_sv.ts
> +                           Vill du spara dom innan du stänger editorn?</translation>
```suggestion
                           Vill du spara dom innan du stänger editorn?
                           
                           %1</translation>
```
Ensure the replaceable-string tag is added back in.

2021-05-12 16:05 UTC, merged

2021-05-12 16:05 UTC, beanpole135 commented
Thanks for fixing that!